[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
minicbor = { version = "2", default-features = false, features = ["alloc", "derive"] }
ed25519-dalek = { version = "3", default-features = false }
blake3 = { version = "1", default-features = false }
proptest = "1"
